# Generated by Django 5.1 on 2024-08-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
